name = "medium"
compatibility_date = "2024-09-21"
compatibility_flags = ["nodejs_compat"]

# Specify the entry point for your Worker
main = "src/index.ts"  # Replace with the actual path to your main Worker script

[vars]
DATABASE_URL = ""
JWT_SECRET=""

# Uncomment and configure these sections as needed
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
